apiVersion: v1
kind: ConfigMap
metadata:
  name: tax-trusted-config
  namespace: tax-trusted
data:
  APP_CORS_ALLOWED_ORIGINS: "https://tax-trusted.example.com"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"

