apiVersion: v1
kind: Secret
metadata:
  name: tax-trusted-secret
  namespace: tax-trusted
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tax_trusted"
  SPRING_DATASOURCE_USERNAME: "tax_trusted"
  SPRING_DATASOURCE_PASSWORD: "change-me"

